import re

with open("Components/MeshHeightAnalysis.cs", "r") as f:
    text = f.read()

if "using Newtonsoft.Json.Linq;" not in text:
    text = "using Newtonsoft.Json.Linq;\n" + text

# Output Parameters
out_params = """        protected override void RegisterOutputParams(GH_OutputParamManager pManager)
        {
            pManager.AddMeshParameter("ColoredMesh", "Mesh", "Mesh with height-based vertex colors", GH_ParamAccess.item);
            pManager.AddNumberParameter("Elevations", "Z", "List of Z elevations corresponding to the mesh vertices", GH_ParamAccess.list);
            pManager.AddCurveParameter("Contours", "C", "Generated contour curves for the terrain", GH_ParamAccess.list);
            pManager.AddTextParameter("Info", "I", "Component information", GH_ParamAccess.item);
            pManager.AddTextParameter("Dashboard JSON", "JSON", "Unified JSON payload containing legend and key analysis metrics for the Analysis Dashboard", GH_ParamAccess.item);
        }"""
text = re.sub(r'        protected override void RegisterOutputParams\(GH_OutputParamManager pManager\)\s*\{[^\}]+\}', out_params, text, flags=re.DOTALL)

# Add JSON logic near the end of SolveInstance
json_logic = """
            if (execute && mesh != null && mesh.IsValid)
            {
                JObject payload = new JObject();
                payload["Title"] = "TERRAIN HEIGHT";
                payload["Type"] = "Gradient";
                
                JArray jcolors = new JArray();
                jcolors.Add(new JObject { ["R"] = 255, ["G"] = 255, ["B"] = 255 }); // example
                if (customColors != null && customColors.Count > 0) {
                    jcolors.Clear();
                    foreach (var c in customColors) jcolors.Add(new JObject { ["R"] = c.R, ["G"] = c.G, ["B"] = c.B });
                }
                payload["Colors"] = jcolors;
                
                JArray jlabels = new JArray();
                jlabels.Add($"{bbox.Min.Z:F2}m");
                jlabels.Add($"{bbox.Max.Z:F2}m");
                payload["Labels"] = jlabels;
                
                double avgZ = 0;
                foreach(var z in zValues) avgZ += z;
                if (zValues.Count > 0) avgZ /= zValues.Count;
                
                JArray jmetrics = new JArray();
                jmetrics.Add(new JObject { ["Name"] = "Min Height", ["Value"] = $"{bbox.Min.Z:F2} m" });
                jmetrics.Add(new JObject { ["Name"] = "Max Height", ["Value"] = $"{bbox.Max.Z:F2} m" });
                jmetrics.Add(new JObject { ["Name"] = "Avg Height", ["Value"] = $"{avgZ:F2} m" });
                payload["Metrics"] = jmetrics;

                DA.SetData(4, payload.ToString(Newtonsoft.Json.Formatting.None));
            }

            DA.SetData(0, coloredMesh);"""
text = text.replace("            DA.SetData(0, coloredMesh);", json_logic)

# Replace Info output text
info_logic = """            DA.SetData(3, "TERRAIN HEIGHT ANALYSIS\\n"
                + "\\n"
                + "METHODOLOGY:\\n"
                + "Extracts Z-coordinates from all mesh vertices to determine absolute elevation ranges. "
                + "Contours are generated by intersecting horizontal planes at specified contour steps with the mesh geometry (Rhino.Geometry.Intersect.Intersection.MeshPlane). "
                + "Colors are mapped by normalizing each vertex's Z-value against the global bounding box Z-range.\\n\\n"
                + "INTERPRETATION & IMPORTANCE:\\n"
                + "Provides immediate visual intuition of localized peaks, basins, and overall site topography, which is critical for planning earthworks, drainage strategies, and building placement.");"""
text = re.sub(r'            DA\.SetData\(3,\s*"TERRAIN HEIGHT ANALYSIS\\n"[^;]+;', info_logic, text, flags=re.DOTALL)

with open("Components/MeshHeightAnalysis.cs", "w") as f:
    f.write(text)

